//created on: Sep 1, 2015
package com.redhat

//list any import classes here.
//declare any global variables here

rule "Validate name"
ruleflow-group "validating"
dialect "mvel"
    when
        $business : Business (name == null);
    then
        insert ( new String( "validation error" ) );
		Reason reason = new Reason();
		reason.setReasonMessage( "no name" );
		insert ( reason );
end

rule "Validate addressLine1"
ruleflow-group "validating"
dialect "mvel"
    when
        $business : Business (addressLine1 == null);
    then
        insert ( new String( "validation error" ) );
		Reason reason = new Reason();
		reason.setReasonMessage( "no addressLine1" );
		insert ( reason );
end

rule "Validate addressLine2"
ruleflow-group "validating"
dialect "mvel"
    when
        $business : Business (addressLine2 == null);
    then
        insert ( new String( "validation error" ) );
		Reason reason = new Reason();
		reason.setReasonMessage( "no addressLine2" );
		insert ( reason );
end

rule "Validate phoneNumber"
ruleflow-group "validating"
dialect "mvel"
    when
        $business : Business (phoneNumber == null);
    then
        insert ( new String( "validation error" ) );
		Reason reason = new Reason();
		reason.setReasonMessage( "no phoneNumber" );
		insert ( reason );
end

rule "Validate city"
ruleflow-group "validating"
dialect "mvel"
    when
        $business : Business (city == null);
    then
        insert ( new String( "validation error" ) );
		Reason reason = new Reason();
		reason.setReasonMessage( "no city" );
		insert ( reason );
end

rule "Validate stateCode"
ruleflow-group "validating"
dialect "mvel"
    when
        $business : Business (stateCode == null);
    then
        insert ( new String( "validation error" ) );
		Reason reason = new Reason();
		reason.setReasonMessage( "no stateCode" );
		insert ( reason );
end

rule "Validate zipCode"
ruleflow-group "validating"
dialect "mvel"
    when
        $business : Business (zipCode == null);
    then
        insert ( new String( "validation error" ) );
		Reason reason = new Reason();
		reason.setReasonMessage( "no zipCode" );
		insert ( reason );
end

rule "Validate federalTaxId"
ruleflow-group "validating"
dialect "mvel"
    when
        $business : Business (federalTaxId == null);
    then
        insert ( new String( "validation error" ) );
		Reason reason = new Reason();
		reason.setReasonMessage( "no federalTaxId" );
		insert ( reason );
end


